const Courses = [
    {
        id: '1',
        title: "Web Development",
        image: require('../assets/webd.jpg'),
    description: "Learn how to build responsive websites using HTML, CSS and JavaScript. This course covers modern front-end development practices and deployment.",
        course1: "HTML",
        course2: "CSS",
        course3: "Javascript",
        Price: 5000,
    },
    {
        id: '2',
        title: "Graphic Designing",
    image: require('../assets/gd.jpg'),
    description: "Master visual design, typography and layout for both print and digital media using Photoshop and Figma.",
        course1: "Photoshop",
        course2: "Figma",
        course3: "Adobe XD",
        Price: 3000,
    }, {
        id: '3',
        title: "Coding Fundamentals",
    image: require('../assets/coding.jpg'),
    description: "Learn programming fundamentals with Java, problem-solving, and tools like IntelliJ to prepare for backend or app development.",
        course1: "Java",
        course2: "IntelliJ",
        Price: 2500,
    },
    {
        id: '4',
        title: "Data Science",
    image: require('../assets/datas.jpg'),
    description: "An introduction to data science covering Python, data analysis, and tools for building machine learning workflows.",
        course1: "Python",
        course2: "Ruby",
        course3: "Pycharm",
        Price: 4000,
    },
    {
        id: '5',
        title: "React-Native",
    image: require('../assets/react.jpg'),
    description: "Build native-like mobile apps using React Native and connect them to Firebase for authentication and data storage.",
        course1: "React",
        course2: "Firebase",
        Price: 5500,
    },
];
export default Courses;